name: emission
channels:
- conda-forge
- defaults
dependencies:
- arrow=1.2.3
- attrdict=2.0.1
- cheroot=9.0.0
- future=0.18.3
- geojson=2.5.0
- google-auth=2.16.0
- jsonpickle=3.0.0
- numpy=1.24.2
- pandas=1.5.3
- pip=23.0
- python-dateutil=2.8.2
- pytz=2022.7.1
- requests=2.28.2
- scikit-learn=1.2.1
- scipy=1.10.0
- utm=0.7.0
- pip:
  - pyfcm==1.5.4
  - pygeocoder==1.2.5
  - pymongo==4.3.3
  - pykov==0.1
prefix: /Users/shankari/OSS/anaconda/envs/emission
