name: emission
channels:
- conda-forge
- defaults
dependencies:
- arrow=1.2.3
- attrdict=2.0.1
- cheroot=9.0.0
- future=0.18.3
- geojson=2.5.0
- jsonpickle=4.0.0
- numpy=1.24.2
- pandas=1.5.3
- pip=25.1
- python-dateutil=2.8.2
- requests=2.32.3
- scikit-learn=1.2.1
- scipy=1.10.0
- utm=0.7.0
- pip:
  - git+https://github.com/JGreenlee/e-mission-common@0.6.4
  - pyfcm==2.0.1
  - pygeocoder==1.2.5
  - pymongo==4.3.3
prefix: /Users/shankari/OSS/anaconda/envs/emission
