name: emission
channels:
- conda-forge
- defaults
dependencies:
- arrow=1.2.3
- attrdict=2.0.1
- cheroot=11.1.2
- future=0.18.3
- geojson=2.5.0
- jsonpickle=4.0.0
- numpy=1.24.2
- pandas=1.5.3
- pip=25.1
- python-dateutil=2.8.2
- requests=2.32.3
- scikit-learn=1.2.1
- scipy=1.10.0
- utm=0.7.0
- pip:
  - git+https://github.com/e-mission/e-mission-common@0.6.5
  - git+https://github.com/wao/AttrDict.git@e47e1bcec4d5c057478a4b5ca3c95bc1c572f8c2
  - pyfcm==2.0.1
  - pygeocoder==1.2.5
  - pymongo==4.6.3
prefix: /Users/shankari/OSS/anaconda/envs/emission
