name: nominatim-docker-test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  
  push:
    branches:
      - nominatim
    paths:
      - 'net/ext_service/geocoder'
      - 'analysis/intake/cleaning/clean_and_resample.py'

  schedule:

    # Run every Sunday at 4:05 am
    - cron:  '5 4 * * 0'
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Workflow test
      run: echo Smoke test

      # Passes the geofabrik key into the docker-compose.yml file. 
    - name: Test nominatim.py
      run: GFBK_KEY=${{ secrets.GEOFABRIK_API }} docker-compose -f emission/integrationTests/docker-compose.yml up --exit-code-from web-server
      

